### ISSUE TITLE
[Tracking] Artificial Intelligence module

### ISSUE THREAD

**Issue by alimulap** [TI-3D/iSentry#6]
- Models
  - Face Detection
  - Landmark Predictor
  - Face Encode Network
  - [x] Detection
  - [x] Recognition
  - [x] Detection then Recognition
- VIdeo processing
  - [x] Real-time video labelling
  - [x] Auto Record chunk save 
- Web server
  - [x] Routes
  - [x] Handlers

**Comment by alimulap** [comment]
Only need minor fixes

Feature complete

Closing
